---

- name: HAPROXY | Install haproxy package
  package:
    name: haproxy
    state: present
  notify: Reload systemd + Restart haproxy

- name: HAPROXY | Manage Rsyslog
  template:
    src: "etc/rsyslog.d/30-haproxy.conf"
    dest: "/etc/rsyslog.d/30-haproxy.conf"
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart rsyslog

- name: HAPROXY | Manage Logrotate
  template:
    src: "etc/logrotate.d/haproxy"
    dest: "/etc/logrotate.d/haproxy"
    owner: root
    group: root
    mode: 0644

- name: HAPROXY | Configuration
  template:
    src: "etc/haproxy/haproxy.cfg.j2"
    dest: "/etc/haproxy/haproxy.cfg"
    owner: root
    group: root
    mode: 0644
  notify: Reload haproxy
  tags: config

- name: HAPROXY | Manage Systemd
  template:
    src: "lib/systemd/system/haproxy.service"
    dest: "/lib/systemd/system/haproxy.service"
    owner: root
    group: root
    mode: 0644
  notify:
    - Reload systemd + Restart haproxy
  when: with_ssl
