---

- name: Reload haproxy
  systemd:
    name: haproxy
    state: reloaded

- name: Restart rsyslog
  systemd:
    name: rsyslog
    state: restarted

- name: Reload systemd + Restart haproxy
  systemd:
    name: haproxy
    state: restarted
    daemon_reload: yes
    enabled: yes
